---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counterapp
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: c1
        image: devopsintellipaat/awseks
        ports:
        - containerPort: 8080
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - nc -z localhost 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /CounterWebApp/
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

---
apiVersion: v1
kind: Service
metadata:
  name: svc
  labels:
    apps: application
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
