---
- name: hosts defined
  hosts: webserver
  become: true
  tasks:
    - name: apache2
      apt: name=apache2 state=latest update_cache=yes
    - name: copy task for tomcat
      copy: src=/var/lib/jenkins/workspace/pipelinenew/target/CounterWebApp.war dest=/var/lib/tomcat9/webapps

